### ISSUE TITLE
 optional field on ImmutableStructure which is nested in a method def - ValueError: wrong parameter order: variadic keyword parameter before positional or keyword parameter 

### ISSUE THREAD

**Issue by dsun-cp** [loyada/typedpy#221]
```
ValueError: wrong parameter order: variadic keyword parameter before positional or keyword parameter 
```

above error from following usage

```
    def hello(self, ...) -> None:
        class FooBar(ImmutableStructure):
            foo: bool
            bar: bool
            foobar: Optional[str]
            barfoo: Optional[str]
```

**Comment by loyada** [comment]
@dsun-cp the code above does not compile (ellipsis is invalid). 
 If I take out the ellipsis:
`
class Foo:
    def hello(self) -> None:
            class FooBar(ImmutableStructure):
                foo: bool
                bar: bool
                foobar: typing.Optional[str]
                barfoo: typing.Optional[str]

            FooBar(foo=True, foobar="", bar=False)
            FooBar(foo=True, bar=False)

Foo().hello()
`

It does not raise an exception. Can you please provide a code snippet that raises the exception you refer to?

**Comment by loyada** [comment]
was finally able to reproduce and fixed. See commit above ^. 
Had nothing to do with optionals or defining within a function.
