### ISSUE TITLE
Versioned types missing the version field have misleading deserialization

### ISSUE THREAD

**Issue by mnazbro** [loyada/typedpy#228]
**Problem**
The typedpy docs state that [the dictionary representing a versioned object must have a `version` field](https://typedpy.readthedocs.io/en/latest/versioning.html#support-for-versioning).

If you try to deserialize a dict without the `version` field, you don't get an error stating that the `version` field is missing. Instead you get a different error unrelated to the `version` field.

**Expectation**
If the dict being deserialized doesn't have a `version` field, a suitable error is thrown.

**Comment by loyada** [comment]
released in 2.19.4. Docs updated.
