### ISSUE TITLE
_additional_serialization is not passed correctly with Omit

### ISSUE THREAD

**Issue by vincent-coastpay-com** [loyada/typedpy#286]
Given:
```
class A(Structure):
  some_field: str
  another_field: str

  @property
  def description(self) -> str:
    return "Some String"

  def _additional_serialization(self) -> dict:
    return {"foo": "bar"}

class B(Omit[A, "another_field"], ImmutableStructure):
  third_field: str

  _serialization_mapper = mappers.TO_CAMELCASE
```

BUG(?):
- If an object of type A, A has a property that be access via `A.description`
- If I do the same for B, I expect `B.description` as well, but I do not.
- B will also not be serialized with {"foo": "bar"}, when it seems like it should be.
- I am basing this issue on my understanding of the docs for how Omit should behave: `Omit creates a new Structure class with all the original fields of the current class, except the ones specified to omit.`

**Comment by loyada** [comment]
This is not a bug, but intentional. It is very easy to introduce nasty bugs otherwise. Updated docs.
